TP_Bibliotheque/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP_Bibliotheque.Models;
using TP_Bibliotheque.Models.DAL;
using TP_Bibliotheque.Models.Data;
using TP_Bibliotheque.Models.ViewModel;

namespace TP_Bibliotheque.Controllers
{
    public class ReservationController : Controller
    {

        public ReservationController() { }

        public ActionResult Index() // récupérer toutes les réservations en cours
        {
            ReservationModelView modelView = new ReservationModelView((List<BooksBorrowing>)Session["BooksBorrowing"]);
            return View(modelView);
        }

        public ActionResult Return(int Id) // Marquer une réservation comme retournée
        {
            // Récupération des réservations en cours
            ReservationDAL dal = new ReservationDAL((List<BooksBorrowing>)Session["BooksBorrowing"]);

            BooksBorrowing resa = dal.Read(Id);

            // Marqué la reservation comme retournée et la mettre à jour
            resa.isReturned = true;
            dal.Update(resa.Id, resa);

            return RedirectToAction("Index");
        }

        public ActionResult Add() // Création d'une nouvelle reservation
        {
            // Récupération data membres + livre
            MemberDAL memberDAL = new MemberDAL((List<Member>)Session["Members"]);
            List<Member> members = memberDAL.GetAll();

            BookDAL bookDAL = new BookDAL((List<Book>)Session["Books"]);
            List<Book> books = bookDAL.GetAvailableBooks();

            // Création de la réservation
            var model = new AddResaViewModel();
            model.members = GetSelectListItemsMember(members);
            model.books = GetSelectListItemsBook(books);
            model.resa = new BooksBorrowing();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "user, book, bookSelected, memberSelected")]AddResaViewModel model)
        {
            // Récupération data réservation + membre + livre
            ReservationDAL dal = new ReservationDAL((List<BooksBorrowing>)Session["BooksBorrowing"]);
            MemberDAL memberDAL = new MemberDAL((List<Member>)Session["Members"]);
            BookDAL bookDAL = new BookDAL((List<Book>)Session["Books"]);

            List<Member> members = memberDAL.GetAll();
            List<Book> books = bookDAL.GetAll();

            model.members = GetSelectListItemsMember(members);
            model.books = GetSelectListItemsBook(books);

            model.resa = new BooksBorrowing();

            // Selection du livre pour la reservation
            Book selectedBook = bookDAL.Read(model.bookSelected);
            model.resa.book = selectedBook;

            // Mise a jour de la quantité disponible
            selectedBook.AvailableQuantity -= 1; 
            bookDAL.Update(selectedBook.Id, selectedBook);

            Member selectedMember = memberDAL.Read(model.memberSelected);
            model.resa.user = selectedMember;

            if (ModelState.IsValid)
            {
                dal.Add(model.resa);
                return RedirectToAction("Index");
            }

            return View("Add", model);
        }

        // FROM http://nimblegecko.com/using-simple-drop-down-lists-in-ASP-NET-MVC/
        // This is one of the most important parts in the whole example.
        // This function takes a list of strings and returns a list of SelectListItem objects.
        // These objects are going to be used later in the SignUp.html template to render the
        // DropDownList.
        private IEnumerable<SelectListItem> GetSelectListItemsMember(IEnumerable<Member> elements)
        {
            // Create an empty list to hold result of the operation
            var selectList = new List<SelectListItem>();

            // For each string in the 'elements' variable, create a new SelectListItem object
            // that has both its Value and Text properties set to a particular value.
            // This will result in MVC rendering each item as:
            //     <option value="State Name">State Name</option>
            foreach (var element in elements)
            {
                selectList.Add(new SelectListItem
                {
                    Value = element.Id.ToString(),
                    Text = element.Firstname + " " + element.Name
                });
            }

            return selectList;
        }

        // FROM http://nimblegecko.com/using-simple-drop-down-lists-in-ASP-NET-MVC/
        // This is one of the most important parts in the whole example.
        // This function takes a list of strings and returns a list of SelectListItem objects.
        // These objects are going to be used later in the SignUp.html template to render the
        // DropDownList.
        private IEnumerable<SelectListItem> GetSelectListItemsBook(IEnumerable<Book> elements)
        {
            // Create an empty list to hold result of the operation
            var selectList = new List<SelectListItem>();

            // For each string in the 'elements' variable, create a new SelectListItem object
            // that has both its Value and Text properties set to a particular value.
            // This will result in MVC rendering each item as:
            //     <option value="State Name">State Name</option>
            foreach (var element in elements)
            {
                selectList.Add(new SelectListItem
                {
                    Value = element.Id.ToString(),
                    Text = element.Title + " (" + element.Author.Name + ")"
                });
            }

            return selectList;
        }


    }
}

TP_Bibliotheque/Views/Reservation/Add.cshtml
@model TP_Bibliotheque.Models.ViewModel.AddResaViewModel
@{
    ViewBag.Title = "Create Resa";
}

<h2>Create Resa</h2>

@using (Html.BeginForm("Create", "Reservation", "POST"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>New reservation</h4>
        <hr />
        
        <div class="form-group">
            @Html.LabelFor(model => model.bookSelected)
            @Html.DropDownListFor(model => model.bookSelected, // 1. Store selected value in Model.State;
                                                               // when page is rendered after postback,
                                                               // take selected value from Model.State.

                                              // 2. Take list of values from Model.States
                                              Model.books,

                                              // 3. Text for the first 'default' option
                                              "- Please select a book -",

                                              //4. A class name to assign to <select> tag
                                              new { @class = "form-control" })
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.memberSelected)
            @Html.DropDownListFor(model => model.memberSelected, // 1. Store selected value in Model.State;
                                                               // when page is rendered after postback,
                                                               // take selected value from Model.State.

                                              // 2. Take list of values from Model.States
                                              Model.members,

                                              // 3. Text for the first 'default' option
                                              "- Please select a member -",

                                              //4. A class name to assign to <select> tag
                                              new { @class = "form-control" })
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TP_Bibliotheque/Views/Reservation/Index.cshtml
@model TP_Bibliotheque.Models.ViewModel.ReservationModelView

@{
    ViewBag.Title = "Liste des reservations.";
}

<h1>Books that have been borrowed</h1>

<ul>
    @foreach (var resa in @Model.GetReservations())
    {
        <li>
            "@resa.user.Name @resa.user.Firstname" borrowed @resa.book.Title (By @resa.book.Author.Name - Edition: @resa.book.Edition) on @resa.beginDate.ToLongDateString() <br />

            @if (resa.isReturned)
            {
                <p>This book has been returned on @resa.returnDate.</p>
            }
            else
            {
                <p>This book has not been returned yet. Limit date @resa.returnDate</p>
                @Html.ActionLink("Return this book", "Return", new { id = resa.Id })
            }

            @if (resa.daysRetard > 0 && !resa.isReturned)
            {
                <p><strong>This member should have returned this book since @resa.daysRetard days  </strong></p>
            }
            <hr/>
        </li>
    }

    @Html.ActionLink("Add Resa", "Add");
</ul>