TP_Bibliotheque/Models/Data/Author.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
namespace TP_Bibliotheque.Models.Data
{
    public class Author : BaseUser
    {

    }
}

TP_Bibliotheque/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP_Bibliotheque.Models;
using TP_Bibliotheque.Models.DAL;
using TP_Bibliotheque.Models.Data;
using TP_Bibliotheque.Models.ViewModel;

namespace TP_Bibliotheque.Controllers
{
    public class AuthorController : Controller
    {

        public AuthorController()
        {
            // TODO Find a way to instanciate this, because it's easier to use than instanciate on the fly in methods
            //dal = new AuthorDAL((List<Author>)Session["Authors"]);
        }

        // GET: Author
        public ActionResult Index() // Pour afficher la liste de tous les auteurs
        {
            AuthorModelView modelView = new AuthorModelView((List<Author>)Session["Authors"]);

            return View(modelView);
        }

        public ActionResult Details(int id) // Pour afficher toutes les infos d'un auteur en particulier
        {
            AuthorDAL authorDAL = new AuthorDAL((List<Author>)Session["Authors"]); // Récupération des auteurs (général)
            BookDAL bookDAL = new BookDAL((List<Book>)Session["Books"]); // Récupération des livres (général)

            Author author = authorDAL.Read(id); // Récupération de l'auteur en particulier

            //Création d'une modelView avec l'auteur + ses livres
            ShowAuthorModelView model = new ShowAuthorModelView(author, bookDAL.FindByAuthor(author)); 
            return View(model);
        }

        public ActionResult Edit(int id) // Edition des informations d'un auteur
        {
            // Récupération des auteurs
            AuthorDAL authorDAL = new AuthorDAL((List<Author>)Session["Authors"]);

            Author author = authorDAL.Read(id); // Lecture des datas de l'auteur en question
            var model = new EditAuthorModelView(); // Création de la modelView de l'edition de l'auteur
            model.author = author; // Ajout de l'auteur a la modelView
            return View(model);
        }

        public ActionResult Delete(int id) // Suppression d'un auteur
        {
            AuthorDAL authorDAL = new AuthorDAL((List<Author>)Session["Authors"]);

            Author author = authorDAL.Read(id); // R2cupération des infos d'un livre pour un id donné
            authorDAL.Delete(id);

            AuthorModelView model = new AuthorModelView((List<Author>)Session["Authors"]);
            return View(model);
        }

        public ActionResult Add() // Ajout d'un nouvel auteur
        {
            Author author = new Author();

            return View(author);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // Création d'un nouvel auteur
        public ActionResult Create([Bind(Include = "Name, Firstname")]Author author)
        {
            AuthorDAL dal = new AuthorDAL((List<Author>)Session["Authors"]);
            if (ModelState.IsValid)
            {
                dal.Add(author);
                return RedirectToAction("Index");
            }

            return View(author);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // Edition d'un auteur existant
        public ActionResult Edition([Bind(Include = "author")]EditAuthorModelView model) // On  récupére l'entity Autheur spécial EditAuthorModelView
        {
            // Récupération des datas d'auteurs
            AuthorDAL dal = new AuthorDAL((List<Author>)Session["Authors"]);
            if (ModelState.IsValid)
            {
                dal.Update(model.author.Id, model.author); // Mise à jour des datas de l'auteur
                return RedirectToAction("Index"); // Retourner à la liste des auteurs si OK
            }

            return View("Edit", model); // Rester sur le formulaire d'edition
        }


    }
}

TP_Bibliotheque/Views/Author/Add.cshtml
@model TP_Bibliotheque.Models.Data.Author
@{
    ViewBag.Title = "Create Author";
}

<h2>Create Author</h2>

@using (Html.BeginForm("Create", "Author", "POST"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TP_Bibliotheque/Views/Author/Delete.cshtml
@{
    ViewBag.Title = "The author has been deleted";
}

<h2>The author has been deleted</h2>

@Html.ActionLink("Return to the author list", "Index", "Author")

TP_Bibliotheque/Views/Author/Details.cshtml
@model TP_Bibliotheque.Models.ViewModel.ShowAuthorModelView

@{
    ViewBag.Title = "Details";
}

<h2>Books written by @Model.getAuthor().Firstname @Model.getAuthor().Name</h2>

<p>This author published @Model.getAuthorBooks().Count book(s)</p>



@if (@Model.getAuthorBooks().Count == 0)
{
      @Html.ActionLink("Delete this author", "Delete", new { id = Model.getAuthor().Id })
}

<ul>
    @foreach (var book in @Model.getAuthorBooks())
    {
        <li>
            @book.Title [@book.PublicationDate.ToLongDateString()] (@book.AvailableQuantity) 
        </li>
    }
</ul>

TP_Bibliotheque/Views/Author/Edit.cshtml
@model TP_Bibliotheque.Models.ViewModel.EditAuthorModelView
@{
    ViewBag.Title = "Edit Author";
}

<h2>Edit Author @Model.author.Id</h2>

@using (Html.BeginForm("Edition", "Author", "POST"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.author.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.HiddenFor(model => model.author.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.author.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.author.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.author.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.author.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.author.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edition" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TP_Bibliotheque/Views/Author/Index.cshtml
@model TP_Bibliotheque.Models.ViewModel.AuthorModelView

@{
    ViewBag.Title = "List of authors";
}

<h1>Authors' list</h1>

<p> To delete an author, please go to the details page of the author. <br />
    You can only delete an author who has not wrote books.</p>

<ul>
    @foreach (var auteur in @Model.GetAuthors())
    {
        <li>
            @auteur.Name @auteur.Firstname id = @auteur.Id @Html.ActionLink("Details", "Details", new { id = auteur.Id}) <br />
            @Html.ActionLink("Edit the author","Edit", new { id = auteur.Id }) 
        </li>
    }

    @Html.ActionLink("Add Author", "Add");
</ul>