TP_Bibliotheque/Models/BooksViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TP_Bibliotheque.Models.Data;

namespace TP_Bibliotheque.Models
{
    public class BooksViewModel
    {
        public List<Book> Books { get; private set; }

        public BooksViewModel()
        {
            Books = new List<Book>();
        }
    }
}

TP_Bibliotheque/Models/Data/Book.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TP_Bibliotheque.Models.Data
{
    public class Book
    {
        public static int IdMax { get; set; }
        [Required]
        public int Id { get; set; }
        public string Title { get; set; }
        public Author Author { get; set; }
        public string Edition { get; set; }
        public DateTime PublicationDate { get; set; }
        public int AvailableQuantity { get; set; }
        public string Thematic { get; set; }

    }
}

TP_Bibliotheque/Models/ViewModel/BooksViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TP_Bibliotheque.Models.Data;

namespace TP_Bibliotheque.Models.ViewModel
{
    public class BooksViewModel
    {
        public List<Book> Books { get; private set; }

        public BooksViewModel()
        {
            Books = new List<Book>();
        }
    }
}

TP_Bibliotheque/Controllers/BookController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TP_Bibliotheque.Models;
using TP_Bibliotheque.Models.DAL;
using TP_Bibliotheque.Models.Data;
using TP_Bibliotheque.Models.ViewModel;

namespace TP_Bibliotheque.Controllers
{
    public class BookController : Controller
    {
        public BookController()
        {
            // TODO Find a way to instanciate this, because it's easier to use than instanciate on the fly in methods
            //dal = new BookDAL((List<Book>)Session["Books"]);
        }

        // GET: Book
        public ActionResult Index()
        {
            BookModelView modelView = new BookModelView((List<Book>)Session["Books"]);

            return View(modelView);
        }

        public ActionResult Add() // Pour l'ajout d'un nouveau livre
        {
            // Récupération des informations sur l'auteur via le form + ajout au model
            AuthorDAL authorDAL = new AuthorDAL((List<Author>)Session["Authors"]);
            List<Author> authors = authorDAL.GetAll();

            var model = new AddBookViewModel();
            model.authors = GetSelectListItems(authors);
            model.book = new Book();
            return View(model);
        }
        
        public ActionResult Edit(int id) // Pour l'édition d'un livre
        {
            // Récupération des infos sur l'auteur
            AuthorDAL authorDAL = new AuthorDAL((List<Author>)Session["Authors"]);
            List<Author> authors = authorDAL.GetAll();

            // Récupération des infos sur le livre
            BookDAL bookDAL = new BookDAL((List<Book>)Session["Books"]);
            Book book = bookDAL.Read(id);

            bookDAL.Update(id, book); // MAJ du livre

            //Données mises à jour renvoyées dans la vue
            var model = new EditBookModelView();
            model.book = book;
            model.authors = GetSelectListItems(authors);

            // Données retournée à la vue
            return View(model);
        }


        public ActionResult Details(int id) // Affichage des informations d'un livre
        {
            BookDAL bookDAL = new BookDAL((List<Book>)Session["Books"]);

            Book book = bookDAL.Read(id); // R2cupération des infos d'un livre pour un id donné
            ShowBookModelView model = new ShowBookModelView(book);
            return View(model);
        }

        public ActionResult Delete(int id) // Affichage des informations d'un livre
        {
            BookDAL bookDAL = new BookDAL((List<Book>)Session["Books"]);

            Book book = bookDAL.Read(id); // R2cupération des infos d'un livre pour un id donné
            bookDAL.Delete(id);

            BookModelView model = new BookModelView((List<Book>)Session["Books"]);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // Création d'un livre à partir d'infos récupéré via un form
        public ActionResult Create([Bind(Include = "book, authorSelected")]AddBookViewModel model)
        {
            // Récupération des datas
            BookDAL dal = new BookDAL((List<Book>)Session["Books"]);
            AuthorDAL authorDAL = new AuthorDAL((List<Author>)Session["Authors"]);

            List<Author> authors = authorDAL.GetAll();

            model.authors = GetSelectListItems(authors); // Récupération de l'auteur
            Author selectedAuthor = authorDAL.Read(model.authorSelected);
            model.book.Author = selectedAuthor; // Ajout de l'auteur au model

            if (ModelState.IsValid)
            {
                dal.Add(model.book); // Ajout du livre
                return RedirectToAction("Index"); // Si tout se passe bien, afficher liste livre
            }

            return View("Add", model); // Si erreur, laissez la view d'ajout
        }


        [HttpPost]
        [ValidateAntiForgeryToken] // Pour l'édition d'un livre
        public ActionResult Edition( [Bind(Include = "book, authorSelected")]EditBookModelView model)
        {
            // Récupération des datas
            BookDAL dal = new BookDAL((List<Book>)Session["Books"]);
            AuthorDAL authorDAL = new AuthorDAL((List<Author>)Session["Authors"]);
            List<Author> authors = authorDAL.GetAll();

            model.authors = GetSelectListItems(authors);
            Author selectedAuthor = authorDAL.Read(model.authorSelected);
            model.book.Author = selectedAuthor;  // Attribuer l'auteur

            if (ModelState.IsValid)
            {
                dal.Update(model.book.Id, model.book); // Mise à jour des datas du livres
                return RedirectToAction("Index"); // Si déroulement OK, retour à la liste de livres
            }

            return View("Edit", model); // Si erreur, on reste sur le formulaire d'edition
        }

        // FROM http://nimblegecko.com/using-simple-drop-down-lists-in-ASP-NET-MVC/
        // This is one of the most important parts in the whole example.
        // This function takes a list of strings and returns a list of SelectListItem objects.
        // These objects are going to be used later in the SignUp.html template to render the
        // DropDownList.
        private IEnumerable<SelectListItem> GetSelectListItems(IEnumerable<Author> elements)
        {
            // Create an empty list to hold result of the operation
            var selectList = new List<SelectListItem>();

            // For each string in the 'elements' variable, create a new SelectListItem object
            // that has both its Value and Text properties set to a particular value.
            // This will result in MVC rendering each item as:
            //     <option value="State Name">State Name</option>
            foreach (var element in elements)
            {
                selectList.Add(new SelectListItem
                {
                    Value = element.Id.ToString(),
                    Text = element.Firstname + " " + element.Name
                });
            }

            return selectList;
        }
    }
}

TP_Bibliotheque/Views/Book/Add.cshtml
@model TP_Bibliotheque.Models.ViewModel.AddBookViewModel
@{
    ViewBag.Title = "Create Book";
}

<h2>Create Author</h2>

@using (Html.BeginForm("Create", "Book", "POST"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.book.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.PublicationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.PublicationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.PublicationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.Thematic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.Thematic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.Thematic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.Edition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.Edition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.Edition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.AvailableQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.AvailableQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.AvailableQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.authorSelected)
            @Html.DropDownListFor(model => model.authorSelected, // 1. Store selected value in Model.State;
                                                            // when page is rendered after postback,
                                                            // take selected value from Model.State.

                                              // 2. Take list of values from Model.States
                                              Model.authors,

                                              // 3. Text for the first 'default' option
                                              "- Please select an author -",

                                              //4. A class name to assign to <select> tag
                                              new { @class = "form-control" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TP_Bibliotheque/Views/Book/Delete.cshtml
@{
    ViewBag.Title = "The book has been deleted";
}

<h2>The book has been deleted</h2>

@Html.ActionLink("Return to the book list", "Index", "Book")

TP_Bibliotheque/Views/Book/Details.cshtml
@model TP_Bibliotheque.Models.ViewModel.ShowBookModelView

@{
    ViewBag.Title = "Details";
}

<h2>Details about this book : @Model.getBook().Title published in @Model.getBook().PublicationDate.ToLongDateString()</h2>

<ul>
    <li>Author : @Model.getBook().Author.Firstname @Model.getBook().Author.Name</li>
    <li>Thematic : @Model.getBook().Thematic</li>
    <li>Edition : @Model.getBook().Edition</li>
    <li>Quantity : @Model.getBook().AvailableQuantity</li>
</ul>

TP_Bibliotheque/Views/Book/Edit.cshtml
@model TP_Bibliotheque.Models.ViewModel.EditBookModelView
@{
    ViewBag.Title = "Edit Book";
}

<h2>Edit book @Model.book.Id</h2>

@using (Html.BeginForm("Edition", "Book", "POST"))
{
    @Html.AntiForgeryToken()

   

    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.book.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.PublicationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.PublicationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.PublicationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.Thematic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.Thematic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.Thematic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.book.Id, new { htmlAttributes = new { @class = "form-control" } });
            @Html.LabelFor(model => model.book.Edition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.Edition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.Edition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.book.AvailableQuantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.book.AvailableQuantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.book.AvailableQuantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.authorSelected)
            @Html.DropDownListFor(model => model.authorSelected, // 1. Store selected value in Model.State;
                                                                 // when page is rendered after postback,
                                                                 // take selected value from Model.State.

                                              // 2. Take list of values from Model.States
                                              Model.authors,

                                              // 3. Text for the first 'default' option
                                              "- Please select an author -",

                                              //4. A class name to assign to <select> tag
                                              new { @class = "form-control" })
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edition" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TP_Bibliotheque/Views/Book/Index.cshtml
@model TP_Bibliotheque.Models.ViewModel.BookModelView

@{
    ViewBag.Title = "Books liste";
}

<h1>Books' list</h1>

<ul>
    @foreach (var book in @Model.GetBooks())
    {
        <li>
            @book.Title [@book.Author.Name] (@book.AvailableQuantity)  @Html.ActionLink("More on this book", "Details", new { id = book.Id }) <br />
                @Html.ActionLink("Edit this book", "Edit", new { id = book.Id }) / @Html.ActionLink("Delete this book", "Delete", new { id = book.Id })
        </li>
    }

    @Html.ActionLink("Add Book", "Add");
</ul>