TP_Bibliotheque/Models/Data/Member.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TP_Bibliotheque.Models.Data
{
    public class Member : BaseUser
    {
        [Required(ErrorMessage = "L'email est obligatoire")]
        public String Email { get; set; }
        public DateTime BirthDate { get; set; }

        public List<BooksBorrowing> BooksBorrowed;


    }
}

TP_Bibliotheque/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP_Bibliotheque.Models.DAL;
using TP_Bibliotheque.Models.Data;
using TP_Bibliotheque.Models.ViewModel;

namespace TP_Bibliotheque.Controllers
{
    public class MemberController : Controller
    {
        // GET: Member
        public ActionResult Index() // Afficher tous les membres
        {
            var dal = new MemberDAL((List<Member>)Session["Members"]);
            var model = new MembersModelView(dal.GetAll());
            return View(model);
        }

        public ActionResult Details(int id) // Affichage des détails d'un membre
        {
            // Récupération des datas du membre : ses données, ses livres emprunté et les datas des livres emprunté
            AuthorDAL authorDAL = new AuthorDAL((List<Author>)Session["Authors"]);
            BookDAL bookDAL = new BookDAL((List<Book>)Session["Books"]);
            MemberDAL memberDAL = new MemberDAL((List<Member>)Session["Members"]);
            ReservationDAL resaDAL = new ReservationDAL((List<BooksBorrowing>)Session["BooksBorrowing"]);

            // Lecture des données du membre selectionne
            Member member = memberDAL.Read(id);
            ShowMemberModelView model = new ShowMemberModelView(member); // Creation de la view d'affichage
            model.Reservations = resaDAL.GetByMember(member); // Récupération des réservations

            return View(model);
        }

        public ActionResult Delete(int id) // Suppression d'un membre
        {
            MemberDAL memberDAL = new MemberDAL((List<Member>)Session["Members"]);

            Member member = memberDAL.Read(id); // R2cupération des infos d'un livre pour un id donné
            memberDAL.Delete(id); // Suppression

            MembersModelView model = new MembersModelView((List<Member>)Session["Members"]);
            return View(model); // Retour à la liste des membres
        }

        public ActionResult Edit(int id) // Pour l'édition du membre
        {
            // Récupération des données de membres + lecture data du membre sélectionné
            MemberDAL memberDAL = new MemberDAL((List<Member>)Session["Members"]);
            Member member = memberDAL.Read(id);

            var model = new EditMemberModelView(); // Création du model d'édition
            model.member = member; // Ajout du membre au model d'edition

            return View(model); // Retour dans la vue des données
        }

        public ActionResult Add() //Ajout d'un nouveau membre
        {
            Member member = new Member();

            return View(member);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // Création d'un nouveau membre
        public ActionResult Create([Bind(Include = "Name, Firstname, BirthDate, Email")]Member member)
        {
            // Récupération des datas des membres
            MemberDAL dal = new MemberDAL((List<Member>)Session["Members"]);
            if (ModelState.IsValid)
            {
                dal.Add(member); //Ajour du nouveau membre à la liste de membres
                return RedirectToAction("Index"); // Retour à la liste des membres
            }

            return RedirectToAction("Add"); // Sinon, rester sur le formulaire d'ajout
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // Pour l'édition d'un membre
        public ActionResult Edition([Bind(Include = "member")]EditMemberModelView model) // Passage en paramètre de l'entité membre
        {
            //Récupération des datas membres
            MemberDAL dal = new MemberDAL((List<Member>)Session["Members"]);
            if (ModelState.IsValid)
            {
                dal.Update(model.member.Id, model.member); // Mise a jour des datas du membre
                return RedirectToAction("Index"); // SI ok, retourner liste des membres
            }

            return View("Edit", model); // Rester sur le formulaire d'edition
        }
    }
}

TP_Bibliotheque/Views/Member/Add.cshtml
@model TP_Bibliotheque.Models.Data.Member
@{
    ViewBag.Title = "Create Member";
}

<h2>Create Member</h2>

@using (Html.BeginForm("Create", "Member", "POST"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TP_Bibliotheque/Views/Member/Delete.cshtml
@{
    ViewBag.Title = "The member has been deleted";
}

<h2>The member has been deleted</h2>

@Html.ActionLink("Return to the member list", "Index", "Member")

TP_Bibliotheque/Views/Member/Details.cshtml
@model TP_Bibliotheque.Models.ViewModel.ShowMemberModelView

@{
    ViewBag.Title = "Details";
}

<h2>Details about @Model.getMember().Firstname @Model.getMember().Name</h2>

<p>
    Email : @Model.getMember().Email
</p>

<p>
    Birthdate : @Model.getMember().BirthDate.ToLongDateString()
</p>

@if (Model.GetReservations().Count <= 0)
{
    <p>This user hasn't borrowed any book yet. You can delete it.<br />
        @Html.ActionLink("Delete this member", "Delete", new { id = Model.getMember().Id })</p>
}

@foreach (var resa in @Model.GetReservations())
{
    <li>
        "@resa.user.Name @resa.user.Firstname" borrowed @resa.book.Title (By @resa.book.Author.Name - Edition: @resa.book.Edition) on @resa.beginDate.ToLongDateString() <br />

        @if (resa.isReturned)
        {
            <p>This book has been returned on @resa.returnDate.</p>
        }
        else
        {
            <p>This book has not been returned yet. Limit date @resa.returnDate</p>
                @Html.ActionLink("Return this book", "Return", new { id = resa.Id })
        }

        @if (resa.daysRetard > 0 && !resa.isReturned)
        {
            <p><strong>This member should have returned this book since @resa.daysRetard days  </strong></p>
        }
        <hr />
    </li>
}

TP_Bibliotheque/Views/Member/Edit.cshtml
@model TP_Bibliotheque.Models.ViewModel.EditMemberModelView
@{
    ViewBag.Title = "Edition Member";
}

<h2>Edit Member @Model.member.Id</h2>

@using (Html.BeginForm("Edition", "Member", "POST"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.member.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.HiddenFor(model => model.member.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model =>model.member.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.member.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.member.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.member.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.member.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.member.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.member.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.member.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.member.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.member.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.member.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edition" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TP_Bibliotheque/Views/Member/Index.cshtml
@model TP_Bibliotheque.Models.ViewModel.MembersModelView

@{
    ViewBag.Title = "Liste des membres enregistrés.";
}

<h1>Members' list</h1>

<ul>
    @foreach (var membre in @Model.GetMembers()) // Parcours de la liste de tous les membres 
    {
        <li>
            @membre.Name @membre.Firstname @Html.ActionLink("Détails", "Details", new { id = membre.Id }) <br />
            @Html.ActionLink("Edit the member", "Edit", new { id = membre.Id })
        </li>
    }

    @Html.ActionLink("Add member", "Add");
</ul>